### ISSUE TITLE
xhulo scammer

### ISSUE THREAD

**Issue by skidghoul** [xhuloo/Fully-Request-AI-Solver#1]
😆

**Comment by skidghoul** [comment]
![image](https://user-images.githubusercontent.com/107319782/185505229-56cb32d8-1587-42d8-a7b8-cbf0710dd5dc.png)

**Comment by xhuloo** [comment]
$10 for what retard

**Comment by skidghoul** [comment]
"I'll send ai solver"
"Ily bae"
